<?php
# This file was automatically generated by the MediaWiki 1.35.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "ChemWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/mediawiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://chemwiki.local";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@chemwiki.local";
$wgPasswordSender = "apache@chemwiki.local";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "chemwiki";
$wgDBuser = "admin";
$wgDBpassword = "vagrant";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "26d8c6503cda75aefab9339cbcab0cdad65dece76645689fce97073b67f79e8e";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "3f81b1c435b08b8f";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'chameleon' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
###############################################################################################################################
# Add more configuration options below.

###############################################################################################################################
#################################################################
# Logos
#################################################################
$wgLogos = ['1x' => "$wgScriptPath/extensions/ChemExtension/resources/KIT-logo.png"];
$wgFavicon = "/extensions/ChemExtension/resources/favicon.ico";

#################################################################
# General settings
#################################################################
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['edit'] = true;
$wgGroupPermissions['user']['read'] = true;
$wgGroupPermissions['contributor']['edit'] = true;

$wgHTTPTimeout = 60;
$wgIgnoreImageErrors=true;
$wgJobRunRate = 100;

$wgUrlProtocols[] = "file://";
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'doc',
    'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx',
    'pptx', 'ps', 'odt', 'ods', 'odp', 'odg'
);

$wgRawHtml = true;

$wgParserCacheType = CACHE_NONE;

$wgPFEnableStringFunctions = true;
$wgStringFunctionsLimitSearch = 5000;
$wgPFStringLengthLimit = 65536;

#Set Default Timezone
$wgLocaltimezone = 'Europe/Berlin';
date_default_timezone_set( $wgLocaltimezone );


#################################################################
# General settings
#################################################################
$wgGenerateThumbnailOnParse = true;

$wgServerHTTP = $wgServer;
$wgWikiServerPath = __DIR__ ;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
$wgHashedUploadDirectory = true;

# deactivate MW autocomplete
$wgEnableOpenSearchSuggest = false;

# Erlaube das "<img>"-tag
$wgAllowImageTag=true;


#################################################################
#
# Include local server settings, if they exist
#
#################################################################
if (file_exists(__DIR__ . '/env.php')) {
    require_once('env.php');
}


#################################################################
# Extensions - SMW
#################################################################
enableSemantics(explode( '://', $wgServer)[1]);

$smwgChangePropagationProtection = false;
$smwgNamespacesWithSemanticLinks[NS_USER] = true;
$smwgNamespacesWithSemanticLinks[NS_CATEGORY] = true;
$smwgShowFactbox = SMW_FACTBOX_HIDDEN;
$smwgShowFactboxEdit = SMW_FACTBOX_HIDDEN;
$smwgBrowseFeatures = SMW_BROWSE_TLINK | SMW_BROWSE_SHOW_INCOMING | SMW_BROWSE_SHOW_GROUP | SMW_BROWSE_SHOW_SORTKEY | SMW_BROWSE_USE_API;
$smwgPageSpecialProperties = array( '_MDAT', '_LEDT', '_CDAT', '_DTITLE' );

## extend allowed complexity of queries
## cf. http://semantic-mediawiki.org/wiki/Help:Configuration#Query_settings
$smwgQMaxSize = 140;
$smwgQPrintoutLimit = 100;

## number of query results
$smwgQDefaultLimit = 200;
$smwgQMaxInlineLimit = 999000;
$smwgQMaxLimit = 999000;
$smwgQUpperbound = 999000;

## disable concept caching
## cf. http://semantic-mediawiki.org/wiki/Help:Configuration#Settings_for_concept_queries and http://semantic-mediawiki.org/wiki/Help:Concept_caching
$smwgQConceptMaxSize = 24;
$smwgQConceptCaching = CONCEPT_CACHE_NONE;
# lifetime in minutes, might be irrelevant for CONCEPT_CACHE_NONE
$smwgQConceptCacheLifetime = 24 * 60;

# also allow iframe-tags in template expansion of query results
use SMW\Query\ResultPrinters\ResultPrinter;
ResultPrinter::$maxRecursionDepth = 8;

# execute updates directly after page-save
# cf. https://www.semantic-mediawiki.org/wiki/Deferred_updates
# and https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledDeferredUpdate
$smwgEnabledDeferredUpdate = false;
//$smwgEnableUpdateJobs=false;
//$smwgEnabledHttpDeferredJobRequest=false;
$smwgFieldTypeFeatures = SMW_FIELDT_CHAR_NOCASE;


#################################################################
# Extensions - PageForms
#################################################################
wfLoadExtension( 'PageForms' );
$wgPageFormsMaxLocalAutocompleteValues = 800;
$wgPageFormsHeightForMinimizingInstances = 800; // default value is 800

$wgPageFormsAutocompleteOnAllChars = true;

global $wgPageFormsDatePickerSettings;
global $wgPageFormsDateTimePickerSettings;
global $wgPageFormsHeightForMinimizingInstances;
$wgPageFormsDatePickerSettings['DateFormat'] = 'dd.mm.yy'; // yy means 4-digits, e.g. 2015
$wgPageFormsDatePickerSettings['ShowResetButton'] = true;
$wgPageFormsDateTimePickerSettings['ShowResetButton'] = true;
$wgPageFormsDateTimePickerSettings['DateFormat'] = 'dd.mm.yy'; // yy means 4-digits, e.g. 2015
$wgAmericanDates = false;


#################################################################
# Visual Editor
#################################################################
wfLoadExtension( 'VisualEditor' );

// OPTIONAL: Enable VisualEditor in other namespaces
// By default, VE is only enabled in NS_MAIN
$wgVisualEditorNamespaces[] = NS_PROJECT;

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';

// OPTIONAL: Enable VisualEditor's experimental code features
//$wgVisualEditorEnableExperimentalCode = true;

wfLoadExtension( 'VEForAll' );
// enable the file upload menu item in the embedded VisualEditor
$wgHooks['VEForAllToolbarConfigNormal'][] = function( &$defaultConfigNormal ) {
    $defaultConfigNormal[4]['include'][] = 'media';
    $defaultConfigNormal[4]['include'][] = 'category';
};


#################################################################
# Powersearch
#################################################################
$fsgShowNamespaces=false;
$fsgShowArticleProperties=false;
$fsgCreateNewPageLink = "/{article}?veaction=edit";


#################################################################
# DisplayTitle
#################################################################
wfLoadExtension( 'DisplayTitle' );
$wgAllowDisplayTitle = true; // defaults to true
$wgRestrictDisplayTitle = false; // defaults to true
$wgDisplayTitleHideSubtitle = true;
$fsgShowSortOrder = true;
$fsgShowCategories = false;
$fsgShowSolrScore = true;


#################################################################
# other Extensions 
#################################################################
// wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'NoTitle' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'Lockdown' );

wfLoadExtension( 'LimitedPageCreator' );


#################################################################
# Chameleon https://www.mediawiki.org/wiki/Skin:Chameleon
#################################################################
wfLoadExtension( 'Bootstrap' );
wfLoadSkin( 'chameleon' );
$wgDefaultSkin='chameleon';
// $egChameleonLayoutFile = __DIR__ . '/extensions/ChemExtension/resources/fixedheadDIQA.xml';
$egChameleonLayoutFile = __DIR__ . '/skins/chameleon/layouts/fixedhead.xml';

//$egChameleonExternalStyleModules = array( __DIR__ . '/extensions/ChemExtension/resources/custom.less' );
// $egChameleonExternalLessVariables = array(
//     'navbar-height' => '50px',
//     'grid-float-breakpoint' => '1000px'
// );
// this enables formedit for the pencil icon for all pages that support forms (no patch needed)
$wgPageformsRenameEditTabs = true;
//currently Chameleon still only reads the SF-version of this variable
$sfgRenameEditTabs = true;



#################################################################
# WikiFarm settings
#################################################################
#
# TODO
#
# $wgArticlePath = '/mediawiki/$1';
# $wgOverrideHostname = 'chemwiki.local';
 require_once ("extensions/WikiFarm/WikiSwitch.php");
 wfLoadExtension('WikiFarm');

$wgPageFormsAutocompletionURLs['molecule_lookup'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>';
$wgPageFormsAutocompletionURLs['molecule_lookup_cat'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>&priorityProperties[]=Catalyst';
$wgPageFormsAutocompletionURLs['molecule_lookup_ps'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>&priorityProperties[]=Photosensitizer';
$wgPageFormsAutocompletionURLs['molecule_lookup_ed'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>&priorityProperties[]=Electron_donor';
$wgPageFormsAutocompletionURLs['molecule_lookup_hd'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>&priorityProperties[]=Hydrogen_donor';
$wgPageFormsAutocompletionURLs['molecule_lookup_solvent'] = $wgServer . $wgScriptPath . '/rest.php/ChemExtension/v1/search-molecule?searchText=<substr>&priorityProperties[]=Solvent';

#################################################################
# Chemistry
#################################################################
 $wgJobRunRate = 0;
define('NS_MOLECULE', 3300);
define('NS_MOLECULE_TALK', 3301);
$wgExtraNamespaces[NS_MOLECULE] = 'Molecule';
$wgExtraNamespaces[NS_MOLECULE_TALK] = 'Molecule_talk';

define('NS_REACTION', 3302);
define('NS_REACTION_TALK', 3303);
$wgExtraNamespaces[NS_REACTION] = 'Reaction';
$wgExtraNamespaces[NS_REACTION_TALK] = 'Reaction_talk';
$smwgNamespacesWithSemanticLinks[NS_MOLECULE] = true;
$smwgNamespacesWithSemanticLinks[NS_REACTION] = true;
$smwgNamespacesWithSemanticLinks[NS_TEMPLATE] = true;
# Enable subpages in the main namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;
wfLoadExtension('ChemExtension');
wfLoadExtension( 'CategoryTree' );
$wgCategoryTreeMaxDepth=4;


#
# Boosting
# changing these values will only take effect after RECREATING the index of the Wiki
# additionally, set this in env.php: $fsgActivateBoosting = true;
#
$fsgActivateBoosting = true;
$fsgDefaultBoost = 5.0;
$fsgCategoryBoosts = [
    'Topic' => 2
];
$fsgTemplateBoosts = [
  // empty
];
$fsgNamespaceBoosts = [
    0    => 2.0,   // Main
    6    => 0.001, // Bild
    8    => 0.001, // Mediawiki
    10   => 0.001, // Vorlage
    12   => 2.0,   // Hilfe
    14   => 2.0, // Kategorie
    102  => 0.001, // Attribut
    106  => 0.001, // Formular
    108  => 0.001, // Konzept
    3300 => 1.5,    // Molekül
    3302 => 1.5,    // Reaction
];

$fsgNamespacesForSearchField = [ NS_MAIN, NS_CATEGORY, NS_MOLECULE, NS_REACTION ];
$wgExternalLinkTarget = '_blank';