<?php
# This file was automatically generated by the MediaWiki 1.35.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# Only for debugging purposes
#error_reporting(E_ALL);
#ini_set( 'display_errors', 1 );

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Chem-Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/mediawiki";
$wgArticlePath = '/mediawiki/$1';

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/Wiki Logo-01.jpg" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "info@diqa-pm.de";
$wgPasswordSender = "noreply@diqa-pm.de";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "chemwiki";
$wgDBuser = "admin";
$wgDBpassword = "vagrant";

#require_once ("extensions/WikiFarm/WikiSwitch.php");

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "de";

$wgSecretKey = "2b4cc2ac22c446ffe0930b95761b74e9d92d13635c59462eb9e52a14d918206b";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "f0d58e470896284b";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "chameleon";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# General settings
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['edit'] = false;

$wgGroupPermissions['user']['read'] = true;

$wgGroupPermissions['contributor']['edit'] = true;

$wgIgnoreImageErrors=true;

# Turn on only for debugging. creates large file
//$wgDebugLogFile = "/var/www/html/mediawiki/mw-log.txt";

$wgHTTPTimeout = 60;
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions=true;

# SMW
enableSemantics( 'chem-wiki.de' );

# PageForms
wfLoadExtension( 'PageForms' );

#################################################################
#
# Chameleon
# https://www.mediawiki.org/wiki/Skin:Chameleon
#
#################################################################

$wgDefaultSkin='chameleon';
$egChameleonLayoutFile = __DIR__ . '/fixedheadDIQA.xml';
//$egChameleonExternalStyleModules = array( __DIR__ . '/custom.less' );
$egChameleonExternalLessVariables = array(
    'navbar-height' => '50px',
    'grid-float-breakpoint' => '1000px'
);
// this enables formedit for the pencil icon for all pages that support forms (no patch needed)
$wgPageformsRenameEditTabs = true;
//currently Chameleon still only reads the SF-version of this variable
$sfgRenameEditTabs = true;

wfLoadExtension( 'NoTitle' );
wfLoadExtension( 'InputBox' );

// Visual Editor
wfLoadExtension( 'VisualEditor' );

// OPTIONAL: Enable VisualEditor in other namespaces
// By default, VE is only enabled in NS_MAIN
//$wgVisualEditorNamespaces[] = NS_PROJECT;

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';

// OPTIONAL: Enable VisualEditor's experimental code features
//$wgVisualEditorEnableExperimentalCode = true;

wfLoadExtension( 'SyntaxHighlight_GeSHi' );

# Powersearch
$fsgShowNamespaces=false;
$fsgShowArticleProperties=false;
$fsgCreateNewPageLink = "/{article}?veaction=edit";

wfLoadExtension( 'VEForAll' );
// enable the file upload menu item in the embedded VisualEditor
$wgHooks['VEForAllToolbarConfigNormal'][] = function( &$defaultConfigNormal ) {
    $defaultConfigNormal[4]['include'][] = 'media';
    $defaultConfigNormal[4]['include'][] = 'category';
};
$wgJobRunRate = 0;

wfLoadExtension( 'Bootstrap' );
wfLoadSkin( 'chameleon' );
wfLoadExtension( 'DisplayTitle' );
$wgAllowDisplayTitle = true; // defaults to true
$wgRestrictDisplayTitle = false; // defaults to true

$wgUrlProtocols[] = "file://";
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'doc',
    'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx',
    'pptx', 'ps', 'odt', 'ods', 'odp', 'odg'
);

wfLoadExtension( 'Lockdown' );

wfLoadExtension( 'LimitedPageCreator' );


wfLoadExtension('ChemExtension');
wfLoadExtension('WikiFarm');
$wgRawHtml = true;

global $IP;
if (!file_exists("$IP/env.php")) {
    trigger_error("$IP/env.php does not exist. Please create!");
    die();
}
require_once "env.php";
