# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine.
    config.vm.network "forwarded_port",  guest: 80, host: 80
    config.vm.network "forwarded_port",  guest: 443, host: 443
    config.vm.network "forwarded_port",  guest: 8080, host: 8080
    config.vm.network "forwarded_port",  guest: 3306, host: 3306
    config.vm.network "forwarded_port",  guest: 8081, host: 8081
    config.vm.network "forwarded_port",  guest: 8983, host: 8983

    # LDAP
    #config.vm.network "forwarded_port",  guest: 389, host: 389
    #config.vm.network "forwarded_port",  guest: 636, host: 636


    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # https://www.vagrantup.com/docs/providers/

    # this setting comes from the vagrant-vbguest plugin -- highly recommended!!
    #     https://github.com/dotless-de/vagrant-vbguest
    # to install the guest-additions
    #     vagrant plugin install vagrant-vbguest
    # set auto_update to false, if you do NOT want to check the correct
    # additions version when booting this machine
    # config.vbguest.auto_update = false


    # VirtualBox
    config.vm.provider "virtualbox" do |v, override|
        v.name = "Chemwiki 1.43 PHP8"
        v.memory = 2024
        v.cpus = 2
        override.vm.provision "shell", path: "bootstrap-ubuntu.sh", privileged: false

        # Every Vagrant virtual environment requires a box to build off of.
        # this is a VirtualBox machine: https://atlas.hashicorp.com/nrel/boxes/CentOS-6.6-x86_64
        config.vm.box = "ubuntu/jammy64"


        # Share an additional folder to the guest VM. The first argument is
        # the path on the host to the actual folder. The second argument is
        # the path on the guest to mount the folder. And the optional third
        # argument is a set of non-required options.
        override.vm.synced_folder "../mediawiki", "/var/www/html/mediawiki"
        override.vm.synced_folder "../wikischema", "/home/vagrant/wikischema"
        override.vm.synced_folder "../wikiimages", "/home/vagrant/wikiimages"
        override.vm.synced_folder "../bin", "/home/vagrant/bin"
        override.vm.synced_folder "../vm", "/vagrant"
    end

end
